FROM lyft/envoy:latest

RUN apt-get update && apt-get -q install -y \
    curl \
    software-properties-common

RUN sudo add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean

# RUN sudo apt-get install default-jre

WORKDIR /app
ADD ./reviews-service/target/reviews-service-0.1.0-SNAPSHOT.jar /app/reviews-service.jar
EXPOSE 9100

ADD ./reviews_envoy.json /etc/reviews_envoy.json
ADD ./reviews_entrypoint.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh

